# Generated by Django 4.2.1 on 2023-05-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotisants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=15)),
                ('nom', models.EmailField(max_length=15)),
                ('solde', models.FloatField()),
                ('date_inscription', models.DateField()),
            ],
        ),
    ]
