# Generated by Django 4.2.1 on 2023-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=25)),
                ('type_produit', models.CharField(choices=[('soda', 'Boisson: Soda'), ('alcool', 'Boisson: Alcool'), ('viennoiserie', 'Viennoiserie'), ('aperitif', 'Apéritif'), ('barre_choco_cereales', 'Barre chocolatée/de céréales'), ('boisson_chaude', 'Boisson: Chaude'), ('autres', 'Autres')], max_length=25)),
                ('quantity', models.IntegerField(default=0)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='date_inscription',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='nom',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='solde',
            field=models.FloatField(default=0),
        ),
    ]
