# Generated by Django 4.2.1 on 2023-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0002_produits_alter_cotisants_date_inscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='nom',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='produits',
            name='type_produit',
            field=models.CharField(choices=[('Boisson: soda', 'soda'), ('Boisson: alcool', 'alcool'), ('Viennoiserie', 'viennoiserie'), ('Apéritif', 'aperitif'), ('Barre chocolatée/de céréales', 'barre_choco_cereales'), ('Boisson: chaude', 'boisson_chaude'), ('Autres', 'autres')], max_length=50),
        ),
    ]
