# Generated by Django 4.2.1 on 2023-05-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0003_alter_produits_nom_alter_produits_type_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisants',
            name='depense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='solde',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='produits',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
