# Generated by Django 4.2.1 on 2023-05-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0004_cotisants_depense_alter_cotisants_solde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisants',
            name='nomprenom',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
