# Generated by Django 4.2.1 on 2023-05-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0007_remove_panier_client_id_remove_panier_client_nom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AlterField(
            model_name='vente',
            name='compte_serveur',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
