# Generated by Django 4.2.1 on 2023-05-27 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0009_remove_vente_prix_remove_vente_produit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.cotisants'),
        ),
    ]
