# Generated by Django 4.2.1 on 2023-05-28 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0011_remove_vente_produits_vente_client_id_vente_prix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connexions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compte_serveur', models.CharField(max_length=30)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='produits',
            name='type_produit',
            field=models.CharField(choices=[('Boisson: soda', 'soda'), ('Boisson: alcool', 'alcool'), ('Viennoiserie', 'viennoiserie'), ('Apéritif', 'aperitif'), ('Barre chocolatée/de céréales', 'barre_choco_cereales'), ('Boisson: chaude', 'boisson_chaude'), ('Boisson: jus', 'jus'), ('Autres', 'autres')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vente',
            name='compte_serveur',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('montant', models.FloatField(default=0)),
                ('compte_serveur', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.cotisants')),
            ],
        ),
        migrations.CreateModel(
            name='AjoutStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('compte_serveur', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('produit_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.produits')),
            ],
        ),
    ]
