# Generated by Django 4.2.1 on 2023-05-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0012_connexions_alter_produits_type_produit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connexions',
            new_name='Connexion',
        ),
    ]
