# Generated by Django 4.2.1 on 2023-05-28 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0013_rename_connexions_connexion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotisants',
            name='date_fin',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='cotisants',
            name='mail',
            field=models.EmailField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='cotisants',
            name='promo',
            field=models.CharField(choices=[('Doctorant', 'Doctorant'), ('Professeur', 'Professeur'), ('Eleve', 'Eleve')], default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='cotisants',
            name='t_cotisation',
            field=models.DurationField(choices=[(datetime.timedelta(days=365), '1 an'), (datetime.timedelta(days=180), '6 mois'), (datetime.timedelta(days=6), '6 jours')], default=None),
        ),
    ]
