# Generated by Django 4.2.1 on 2023-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0014_cotisants_date_fin_cotisants_mail_cotisants_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='t_cotisation',
            field=models.IntegerField(choices=[(365, '1 an'), (180, '6 mois'), (6, '6 jours')], default=None),
        ),
    ]
