# Generated by Django 4.2.1 on 2023-05-28 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0017_alter_cotisants_date_inscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotisants',
            old_name='t_cotisation',
            new_name='temps_cotisation',
        ),
    ]
