# Generated by Django 4.2.1 on 2023-05-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0018_rename_t_cotisation_cotisants_temps_cotisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('client', models.CharField(max_length=50)),
                ('compte_serveur', models.CharField(max_length=30)),
                ('date_connexion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='solde',
            field=models.FloatField(),
        ),
    ]
