# Generated by Django 4.2.1 on 2023-05-28 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0019_supvente_alter_cotisants_solde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supvente',
            old_name='date_connexion',
            new_name='date_suppression',
        ),
    ]
