# Generated by Django 4.2.1 on 2023-05-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0021_alter_cotisants_depense_alter_encaissement_montant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='solde',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.CreateModel(
            name='FavorisTipause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.produits')),
            ],
        ),
        migrations.CreateModel(
            name='FavorisTibbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.produits')),
            ],
        ),
    ]
