# Generated by Django 4.2.1 on 2023-05-28 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0022_alter_cotisants_solde_favoristipause_favoristibbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoristibbar',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.produits', unique=True),
        ),
        migrations.AlterField(
            model_name='favoristipause',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.produits', unique=True),
        ),
    ]
