# Generated by Django 4.2.1 on 2023-05-28 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0024_alter_favoristibbar_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoristibbar',
            name='produit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favoris_tibbar', to='AppCotisants.produits'),
        ),
    ]
