# Generated by Django 4.2.1 on 2023-05-29 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0026_alter_favoristipause_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCotisants.vente')),
            ],
        ),
    ]
