# Generated by Django 4.2.1 on 2023-05-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0027_ventesstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatesStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='VentesStat',
        ),
    ]
