# Generated by Django 4.2.1 on 2023-06-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0034_alter_produits_type_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='promo',
            field=models.CharField(max_length=40),
        ),
    ]
