# Generated by Django 4.2.1 on 2023-06-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0037_alter_cotisants_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='promo',
            field=models.CharField(choices=[('Doctorant', 'Doctorant'), ('Professeur', 'Professeur'), ('Eleve', 'Eleve')], default=None, max_length=40),
        ),
    ]
