# Generated by Django 4.2.1 on 2023-06-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0038_alter_cotisants_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='nomprenom',
            field=models.CharField(default='unique', max_length=30),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='promo',
            field=models.CharField(default='', max_length=40),
        ),
    ]
