# Generated by Django 4.2.1 on 2023-06-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0039_alter_cotisants_nomprenom_alter_cotisants_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisants',
            name='depense',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='nomprenom',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='cotisants',
            name='solde',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=8),
        ),
    ]
