# Generated by Django 4.2.1 on 2023-06-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCotisants', '0041_ajoutstock_ancien_prix_ajoutstock_nouv_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupCot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('compte_serveur', models.CharField(max_length=30)),
                ('date_suppression', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
